import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chas Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-[#201430] text-white" lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
