// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chas Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="font-manrope bg-[#110A1A] text-white" lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
