import "./globals.css";
import Navbar from "./components/Navbar";
import { SearchProvider } from "./context/SearchContext";
import { AuthProvider } from "./context/AuthContext";

export const metadata = {
  title: "LUDI - Your Go-To Place for Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="font-manrope bg-black  text-white" lang="en">
      <body>
        <AuthProvider>
          <SearchProvider>
            <Navbar />
            {children}
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
