version: "3"
services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my_custom_network

  express:
    build: ./backend
    ports:
      - "3010:3010"
    networks:
      - my_custom_network

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie-app-sql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_custom_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
    depends_on:
      - nextjs
      - express
    networks:
      - my_custom_network

volumes:
  mysql-data:

networks:
  my_custom_network:
    external: true
